# Generated by Django 2.1.2 on 2018-10-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_number', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('maximum_load_capacity', models.IntegerField()),
                ('current_weight', models.IntegerField()),
                ('overload', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
    ]
