# Generated by Django 2.1.2 on 2018-10-05 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='truck',
            old_name='board_number',
            new_name='бортовой_номер',
        ),
        migrations.RenameField(
            model_name='truck',
            old_name='current_weight',
            new_name='максимальная_грузоподьемность',
        ),
        migrations.RenameField(
            model_name='truck',
            old_name='model',
            new_name='модель',
        ),
        migrations.RenameField(
            model_name='truck',
            old_name='overload',
            new_name='перегруз',
        ),
        migrations.RenameField(
            model_name='truck',
            old_name='maximum_load_capacity',
            new_name='текущий_вес',
        ),
    ]
