# Generated by Django 2.1.2 on 2018-10-05 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_remove_truck_перегруз'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Truck',
            new_name='Dump_Truck',
        ),
    ]
