# Generated by Django 2.1.2 on 2018-10-06 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20181005_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dump_truck',
            old_name='максимальная_грузоподьемность',
            new_name='current_weight',
        ),
        migrations.RenameField(
            model_name='dump_truck',
            old_name='текущий_вес',
            new_name='max_load',
        ),
        migrations.RenameField(
            model_name='dump_truck',
            old_name='бортовой_номер',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='dump_truck',
            old_name='модель',
            new_name='number',
        ),
    ]
