# Generated by Django 2.1.2 on 2018-10-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20181006_0849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dump_truck',
            options={'verbose_name': 'Самосвалы'},
        ),
        migrations.AlterField(
            model_name='dump_truck',
            name='current_weight',
            field=models.IntegerField(verbose_name='Текущий вес'),
        ),
        migrations.AlterField(
            model_name='dump_truck',
            name='max_load',
            field=models.IntegerField(verbose_name='Максимальная грузоподъемность'),
        ),
        migrations.AlterField(
            model_name='dump_truck',
            name='model',
            field=models.CharField(max_length=20, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='dump_truck',
            name='number',
            field=models.CharField(max_length=20, verbose_name='Бортовой номер'),
        ),
    ]
