# Generated by Django 2.1.2 on 2018-10-06 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_auto_20181006_0919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dump_truck',
            options={'verbose_name': 'Самосвал', 'verbose_name_plural': 'Самосвалы'},
        ),
    ]
