# Generated by Django 2.1.2 on 2018-10-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_auto_20181006_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='dump_truck',
            name='overload',
            field=models.IntegerField(default=0, verbose_name='Перегруз'),
            preserve_default=False,
        ),
    ]
