# Generated by Django 2.1.2 on 2018-10-06 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_dump_truck_overload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dump_truck',
            name='overload',
        ),
    ]
