# Generated by Django 2.1.2 on 2018-10-06 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_remove_dump_truck_overload'),
    ]

    operations = [
        migrations.CreateModel(
            name='DumpTruck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Бортовой номер')),
                ('model', models.CharField(max_length=20, verbose_name='Модель')),
                ('current_weight', models.IntegerField(verbose_name='Текущий вес')),
            ],
            options={
                'verbose_name_plural': 'Самосвалы',
                'verbose_name': 'Самосвал',
            },
        ),
        migrations.CreateModel(
            name='DumpTruckModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=20, verbose_name='Модель')),
                ('max_load', models.IntegerField(verbose_name='Максимальная грузоподъемность')),
            ],
            options={
                'verbose_name_plural': 'Характеристики моделелей самосвалов',
                'verbose_name': 'Характеристики моделелей самосвала',
            },
        ),
        migrations.DeleteModel(
            name='Dump_Truck',
        ),
    ]
